defgp2;

omega_n=20;
zeta=0.7;
alpha=zeta*omega_n;
M=omega_n^2*alpha/((s^2+2*zeta*omega_n*s+omega_n^2)*(s+alpha));
Gff=ss(M/tf(P.nominal));
P.y='y';
P.u='u';
K.y='ufb';
K.u='e';
Gff.y='uff';
Gff.u='r';
M.y='yr';
M.u='r';
sum1=sumblk('u=uff+ufb');
sum2=sumblk('e=yr-y');
Gtdof=connect(P,K,Gff,M,sum1,sum2,'r',{'y','u'});
figure();
subplot(211);
step(Gtdof(1,1),1);
ylim([0 1.2]);
subplot(212);
step(Gtdof(2,1),2);
ylim([-5 5]);
big;


omega_n=50;
zeta=0.7;
alpha=zeta*omega_n;
M=omega_n^2*alpha/((s^2+2*zeta*omega_n*s+omega_n^2)*(s+alpha));
Gff=ss(M/tf(P.nominal));
P.y='y';
P.u='u';
K.y='ufb';
K.u='e';
Gff.y='uff';
Gff.u='r';
M.y='yr';
M.u='r';
sum1=sumblk('u=uff+ufb');
sum2=sumblk('e=yr-y');
Gtdof=connect(P,K,Gff,M,sum1,sum2,'r',{'y','u'});
figure();
subplot(211);
step(Gtdof(1,1),1);
ylim([0 1.2]);
subplot(212);
step(Gtdof(2,1),2);
ylim([-5 5]);
big;